// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.MiniProfiler;

namespace Migrator.Migrations.MiniProfilerDb
{
    [DbContext(typeof(MiniProfilerDbContext))]
    partial class MiniProfilerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persistence.MiniProfiler.MiniProfilerClientTimings", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MiniProfilerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Start")
                        .HasColumnType("decimal(9,3)");

                    b.HasKey("RowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MiniProfilerId");

                    b.ToTable("MiniProfilerClientTimings");
                });

            modelBuilder.Entity("Persistence.MiniProfiler.MiniProfilerTimings", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomTimingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Depth")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DurationMilliseconds")
                        .HasColumnType("decimal(15,3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("bit");

                    b.Property<Guid>("MiniProfilerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid?>("ParentTimingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StartMilliseconds")
                        .HasColumnType("decimal(15,3)");

                    b.HasKey("RowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MiniProfilerId");

                    b.ToTable("MiniProfilerTimings");
                });

            modelBuilder.Entity("Persistence.MiniProfiler.MiniProfilers", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientTimingsRedirectCount")
                        .HasColumnType("int");

                    b.Property<string>("CustomLinksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DurationMilliseconds")
                        .HasColumnType("decimal(15,1)");

                    b.Property<bool>("HasUserViewed")
                        .HasColumnType("bit");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid?>("RootTimingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("RowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("User", "HasUserViewed")
                        .HasAnnotation("SqlServer:Include", new[] { "Id", "Started" });

                    b.ToTable("MiniProfilers");
                });
#pragma warning restore 612, 618
        }
    }
}
